# Generated by Django 3.2.4 on 2021-06-03 22:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=15, verbose_name='Gender')),
            ],
            options={
                'verbose_name': 'gender',
                'verbose_name_plural': 'gender',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default=None, max_length=20, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(default='Null', max_length=25, verbose_name='Nationality')),
            ],
            options={
                'verbose_name': 'nationality',
                'verbose_name_plural': 'nationality',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=0, max_length=8, verbose_name='Number')),
                ('date_from', models.DateField(default=datetime.date.today, verbose_name='Date_from')),
                ('date_to', models.DateField(default=datetime.date.today, verbose_name='Date_to')),
            ],
            options={
                'verbose_name': 'passport',
                'verbose_name_plural': 'passport',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('birthday', models.DateField(default=datetime.date.today, verbose_name='Birthday')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.gender', verbose_name='gender')),
                ('languages', models.ManyToManyField(related_name='languages', to='home.Languages', verbose_name='language')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.nationality', verbose_name='nationality')),
                ('passport', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.passport')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'person',
            },
        ),
    ]
