# Generated by Django 3.2.4 on 2021-06-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210605_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.CharField(max_length=8, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.gender', verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.nationality', verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='person',
            name='passport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.passport', unique=True),
        ),
    ]
