# Generated by Django 3.2.4 on 2021-06-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210605_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='passport',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.passport'),
        ),
    ]
